-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 14:57:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mentevida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mentevida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mentevida` DEFAULT CHARACTER SET utf8mb4 ;
USE `mentevida` ;

-- -----------------------------------------------------
-- Table `mentevida`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`paciente` (
  `id_paciente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `historico_medico` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`medico` (
  `id_medico` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(256) NULL,
  `cargo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_medico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`consulta` (
  `id_consulta` INT(11) NOT NULL AUTO_INCREMENT,
  `duracao` INT NOT NULL,
  `valor` DOUBLE NULL,
  `id_paciente` INT(11) NULL DEFAULT NULL,
  `id_medico` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_consulta`),
  INDEX `id_paciente` (`id_paciente` ASC) ,
  INDEX `id_medico` (`id_medico` ASC) ,
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `mentevida`.`paciente` (`id_paciente`),
  CONSTRAINT `consulta_ibfk_2`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mentevida`.`medico` (`id_medico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`funcionario` (
  `id_funcionario` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(256) NULL,
  `cargo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`prescricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`prescricao` (
  `id_prescricao` INT(11) NOT NULL AUTO_INCREMENT,
  `data_prescricao` DATE NOT NULL,
  `medicamentos` TEXT NULL DEFAULT NULL,
  `dosagem` VARCHAR(100) NULL DEFAULT NULL,
  `id_consulta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_prescricao`),
  INDEX `id_consulta` (`id_consulta` ASC) ,
  CONSTRAINT `prescricao_ibfk_1`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `mentevida`.`consulta` (`id_consulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`relatorio` (
  `id_relatorio` INT(11) NOT NULL AUTO_INCREMENT,
  `data_relatorio` DATE NOT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `consulta_id_consulta` INT(11) NOT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `fk_relatorio_consulta1_idx` (`consulta_id_consulta` ASC) ,
  CONSTRAINT `fk_relatorio_consulta1`
    FOREIGN KEY (`consulta_id_consulta`)
    REFERENCES `mentevida`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mentevida`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mentevida`.`agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATE NULL,
  `status` TINYINT NULL,
  `paciente_id_paciente` INT(11) NOT NULL,
  `medico_id_medico` INT(11) NOT NULL,
  `funcionario_id_funcionario` INT(11) NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_agendamento_paciente1_idx` (`paciente_id_paciente` ASC) ,
  INDEX `fk_agendamento_medico1_idx` (`medico_id_medico` ASC) ,
  INDEX `fk_agendamento_atendente1_idx` (`funcionario_id_funcionario` ASC) ,
  CONSTRAINT `fk_agendamento_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `mentevida`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `mentevida`.`medico` (`id_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_atendente1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mentevida`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
